In [2]:
import pandas as pd
df = pd.read_csv("top.csv")
df

,Unnamed: 0,SN,Movie,Worldwide,India Net,India Gross,Overseas,Budget,Verdict
0,0,1,Pathaan,10500000000,5240000000,6570000000,3920000000,2500000000,All Time Blockbuster
1,1,2,Baahubali 2 The Conclusion,17880000000,5100000000,14160000000,3710000000,2500000000,All Time Blockbuster
2,2,3,KGF Chapter 2,12080000000,4350000000,10000000000,2070000000,1000000000,All Time Blockbuster
3,3,4,Dangal,20700000000,3740000000,5350000000,15350000000,700000000,All Time Blockbuster
4,4,5,Sanju,5880000000,3420000000,4380000000,1500000000,1000000000,All Time Blockbuster
...,...,...,...,...,...,...,...,...,...
995,995,996,Nikamma,0,20000000,20000000,0,10000000,0
996,996,997,Saugandh,30000000,20000000,30000000,0,20000000,Average
997,997,998,Akaash Vani,30000000,20000000,20000000,0,100000000,Disaster
998,998,999,Zwigato,10000000,20000000,10000000,0,10000000,0
999,999,1000,FryDay,20000000,20000000,20000000,0,150000000,Disaster

In [3]:
df.columns

Index(['Unnamed: 0', 'SN', 'Movie', 'Worldwide', 'India Net', 'India Gross',
       'Overseas', 'Budget', 'Verdict'],
      dtype='object')

In [4]:
df.head()

,Unnamed: 0,SN,Movie,Worldwide,India Net,India Gross,Overseas,Budget,Verdict
0,0,1,Pathaan,10500000000,5240000000,6570000000,3920000000,2500000000,All Time Blockbuster
1,1,2,Baahubali 2 The Conclusion,17880000000,5100000000,14160000000,3710000000,2500000000,All Time Blockbuster
2,2,3,KGF Chapter 2,12080000000,4350000000,10000000000,2070000000,1000000000,All Time Blockbuster
3,3,4,Dangal,20700000000,3740000000,5350000000,15350000000,700000000,All Time Blockbuster
4,4,5,Sanju,5880000000,3420000000,4380000000,1500000000,1000000000,All Time Blockbuster

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   SN           1000 non-null   int64
 2   Movie        1000 non-null   object
 3   Worldwide    1000 non-null   int64
 4   India Net    1000 non-null   int64
 5   India Gross  1000 non-null   int64
 6   Overseas     1000 non-null   int64
 7   Budget       1000 non-null   int64
 8   Verdict      1000 non-null   object
dtypes: int64(7), object(2)
memory usage: 70.4+ KB

In [6]:
df.isnull().sum()

Unnamed: 0     0
SN             0
Movie          0
Worldwide      0
India Net      0
India Gross    0
Overseas       0
Budget         0
Verdict        0
dtype: int64

In [7]:
df.drop(columns=['Unnamed: 0','SN','Movie'],inplace = True)
df

,Worldwide,India Net,India Gross,Overseas,Budget,Verdict
0,10500000000,5240000000,6570000000,3920000000,2500000000,All Time Blockbuster
1,17880000000,5100000000,14160000000,3710000000,2500000000,All Time Blockbuster
2,12080000000,4350000000,10000000000,2070000000,1000000000,All Time Blockbuster
3,20700000000,3740000000,5350000000,15350000000,700000000,All Time Blockbuster
4,5880000000,3420000000,4380000000,1500000000,1000000000,All Time Blockbuster
...,...,...,...,...,...,...
995,0,20000000,20000000,0,10000000,0
996,30000000,20000000,30000000,0,20000000,Average
997,30000000,20000000,20000000,0,100000000,Disaster
998,10000000,20000000,10000000,0,10000000,0
999,20000000,20000000,20000000,0,150000000,Disaster

In [8]:
df.duplicated().sum()

np.int64(13)

In [9]:
df.drop_duplicates(inplace=True,ignore_index=True)

In [10]:
df['Success'] = df['Verdict'].replace({
    'All Time Blockbuster':'Hit',
    'Blockbuster':'Hit',
    'SuperHit':'Hit',
    'Hit':'Hit',
    'Above Average':'Not Hit',
    'Average':'Not Hit',
    'Below Average':'Not Hit',
    'Flop':'Not Hit',
    'Disaster':'Not Hit'
})

In [11]:
df['Verdict'].unique()

array(['All Time Blockbuster', 'Blockbuster', 'Hit', 'SuperHit',
       'Average', 'Below Average', 'Disaster', 'Flop', 'Above Average',
       '0'], dtype=object)

In [12]:
(df['Verdict'] == '0').sum()

np.int64(50)

In [13]:
df = df[df['Verdict'] != '0']

In [14]:
df['Verdict'].unique()

array(['All Time Blockbuster', 'Blockbuster', 'Hit', 'SuperHit',
       'Average', 'Below Average', 'Disaster', 'Flop', 'Above Average'],
      dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Success']= le.fit_transform(df['Success'])
df

/var/folders/cn/typknvzx0rqc0bg_wj2zt_t00000gn/T/ipykernel_6789/2805435822.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Success']= le.fit_transform(df['Success'])

,Worldwide,India Net,India Gross,Overseas,Budget,Verdict,Success
0,10500000000,5240000000,6570000000,3920000000,2500000000,All Time Blockbuster,0
1,17880000000,5100000000,14160000000,3710000000,2500000000,All Time Blockbuster,0
2,12080000000,4350000000,10000000000,2070000000,1000000000,All Time Blockbuster,0
3,20700000000,3740000000,5350000000,15350000000,700000000,All Time Blockbuster,0
4,5880000000,3420000000,4380000000,1500000000,1000000000,All Time Blockbuster,0
...,...,...,...,...,...,...,...
976,520000000,20000000,480000000,40000000,400000000,Average,1
981,30000000,20000000,30000000,0,150000000,Flop,1
983,30000000,20000000,30000000,0,20000000,Average,1
984,30000000,20000000,20000000,0,100000000,Disaster,1
986,20000000,20000000,20000000,0,150000000,Disaster,1

In [16]:
X = df.drop(['Verdict','Success'],axis=1)
y = df['Success']
X

       Worldwide   India Net  India Gross     Overseas      Budget
0    10500000000  5240000000   6570000000   3920000000  2500000000
1    17880000000  5100000000  14160000000   3710000000  2500000000
2    12080000000  4350000000  10000000000   2070000000  1000000000
3    20700000000  3740000000   5350000000  15350000000   700000000
4     5880000000  3420000000   4380000000   1500000000  1000000000
..           ...         ...          ...          ...         ...
976    520000000    20000000    480000000     40000000   400000000
981     30000000    20000000     30000000            0   150000000
983     30000000    20000000     30000000            0    20000000
984     30000000    20000000     20000000            0   100000000
986     20000000    20000000     20000000            0   150000000

[937 rows x 5 columns]

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X,y,test_size=0.2,random_state=42)

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
model = SVC(kernel='linear')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7127659574468085

In [20]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, rf_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8457446808510638

In [21]:

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

from sklearn.metrics import accuracy_score
print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))

Logistic Regression Accuracy: 0.7287234042553191

In [22]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

print("KNN Accuracy:", accuracy_score(y_test, knn_pred))

KNN Accuracy: 0.8936170212765957

In [23]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))

Decision Tree Accuracy: 0.8404255319148937

In [24]:
print(le.classes_)

['Hit' 'Not Hit']

In [25]:
import joblib

joblib.dump(model, "svm.pkl")
joblib.dump(rf, "rf.pkl")
joblib.dump(dt, "dt.pkl")
joblib.dump(knn, "knn.pkl")
joblib.dump(lr, "lr.pkl")

joblib.dump(scaler, "scaler.pkl")
joblib.dump(le, "label_encoder.pkl")

['label_encoder.pkl']